version: '3'

services:
  app:
    image: next-docker-image
    build: .
    ports:
      - 3000:3000
    network_mode: "host"
    volumes:
      - ./.next:/nextDirecto/.next
      - ./.env:/nextDirecto/.env
      - ./public:/nextDirecto/public
