const typography = {
  desktop: {
    link: " lg:text-base ",
    Btn: " lg:text-lg",
    heroheading: " lg:text-7xl",
    heroheading1: "  lg:text-7xl",
    heropara: "  lg:text-[18px]",
    herobtn: " lg:text-[18px]",
    Serviceheading: " lg:text-sm",
    Serviceboldheading: " lg:text-[48px]",
    ServiceCardheading: " lg:text-[25px]",
    ServiceCardpara: " lg:text-[17px]",
    Aboutheading: " lg:text-[24px]",
    Aboutboldheading: " lg:text-[48px]",
    Aboutpara: " lg:text-[18px]",
    Aboutlink: " lg:text-[18px]",
    Clientheading: " lg:text-[24px]",
    Testimonialsheading: " lg:text-[48px]",
    TestimonialsPara: " lg:text-[18px]",
    SubscribeHeading: " lg:text-[48px]",
    SubscribePara: " lg:text-[18px]",
  },
  tablet: {
    link: "md:text-base ",
    Btn: "md:text-lg",
    heroheading: "md:text-[72px]",
    heroheading1: "md:text-[72px]",
    heropara: "md:text-[18px]",
    herobtn: "md:text-[18px]",
    Serviceheading: "md:text-[48px]",
    Serviceboldheading: "md:text-[33px]",
    ServiceCardheading: "md:text-[17px]",
    ServiceCardpara: "md:text-[17px]",
    Aboutheading: "md:text-[48px]",
    Aboutboldheading: "md:text-[33px]",
    Aboutpara: "md:text-[18px]",
    Aboutlink: "md:text-[22px]",
    Clientheading: "md:text-[48px]",
    Testimonialsheading: "md:text-[33px]",
    TestimonialsPara: "md:text-[12px]",
    SubscribeHeading: "md:text-[33px]",
    SubscribePara: "md:text-[18px]",
  },
  mobile: {
    link: "text-[11px]",
    heroheading: "text-[31px]",
    heroheading1: "text-[31px]",
    heropara: "text-[10px]",
    herobtn: "text-[11px]",
    Serviceheading: "text-[24px]",
    Serviceboldheading: "text-[18px]",
    ServiceCardheading: "text-[13px]",
    ServiceCardpara: "text-[10px]",
    Aboutheading: "text-[24px]",
    Aboutboldheading: "text-[18px]",
    Aboutpara: "text-[10px]",
    Aboutlink: "text-[9px]",
    Clientheading: "text-[24px]",
    Testimonialsheading: "text-[21px]",
    TestimonialsPara: "text-[9px]",
    SubscribeHeading: "text-[21px]",
    SubscribePara: "text-[10px]",
  },
};
export { typography };
